version: "3"
services:
  api:
    build: .
    image: node-server
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    