version: "3"
services:
  api:
    build: .
    image: api
    container_name: api
    command: npm run start
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    container_name: api_db
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"
volumes:
   mongodb_api:
    